### ISSUE TITLE
launch `ros2 pkg prefix movidius_ncs_launch`/share/movidius_ncs_launch/launch/ncs_image_launch.py  occurs an error

### ISSUE THREAD

**Issue by RachelRen05** [intel/ros2_intel_movidius_ncs#13]
When
`launch `ros2 pkg prefix movidius_ncs_launch`/share/movidius_ncs_launch/launch/ncs_image_launch.py`
**Error description:**
Traceback (most recent call last):
  File "/home/renzhen/ros2_ws/install/bin/launch", line 11, in <module>
    load_entry_point('launch==0.4.0', 'console_scripts', 'launch')()
  File "/home/renzhen/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/renzhen/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/renzhen/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/renzhen/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/renzhen/ros2_ws/install/lib/python3.5/site-packages/launch/main.py", line 19, in <module>
    from launch import LaunchDescriptor
ImportError: cannot import name 'LaunchDescriptor'

**Comment by RachelRen05** [comment]
The python path in my environment is
**/home/renzhen/ros2_ws/install/lib/python3.5/site-packages::/opt/movidius/caffe/python**
The `__init__.py` file under the **/home/renzhen/ros2_ws/install/lib/python3.5/site-packages/launch** path is empty
When I copied the `__init__.py` from the **ardent** directory,it worked.
